name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Build with Vercel
      run: |
        npm i -g vercel
        echo "Building project..."
        vercel build --prod
    
    - name: Deploy to Vercel
      run: |
        echo "Deploying to Vercel..."
        # This will prompt for token or use existing auth